version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    networks:
      - quiz-net
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - quiz-net

networks:
  quiz-net:
    driver: bridge
